USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS ETL_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  COMMENT        = 'ETL Agent warehouse — auto-suspends after 60s';

CREATE DATABASE IF NOT EXISTS FINANCE_ETL_DEMO
  COMMENT = 'Autonomous Finance ETL Demo';

CREATE SCHEMA IF NOT EXISTS FINANCE_ETL_DEMO.RAW
  COMMENT = 'Bronze layer — raw ingested data';

CREATE SCHEMA IF NOT EXISTS FINANCE_ETL_DEMO.STAGING
  COMMENT = 'Silver layer — cleaned & enriched data';

CREATE SCHEMA IF NOT EXISTS FINANCE_ETL_DEMO.ANALYTICS
  COMMENT = 'Gold layer — aggregated business-ready data';

CREATE SCHEMA IF NOT EXISTS FINANCE_ETL_DEMO.AUDIT
  COMMENT = 'ETL audit logs, run history, alerts';

USE WAREHOUSE ETL_WH;
USE DATABASE  FINANCE_ETL_DEMO;
