USE SCHEMA RAW;

CREATE OR REPLACE STREAM RAW.STR_CUSTOMERS    ON TABLE RAW.CUSTOMERS    APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM RAW.STR_ACCOUNTS     ON TABLE RAW.ACCOUNTS     APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM RAW.STR_TRANSACTIONS ON TABLE RAW.TRANSACTIONS APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM RAW.STR_RISK_EVENTS  ON TABLE RAW.RISK_EVENTS  APPEND_ONLY = TRUE;
