CREATE OR REPLACE TASK AUDIT.TASK_ETL_ORCHESTRATOR
  WAREHOUSE = ETL_WH
  SCHEDULE  = '15 MINUTE'
  COMMENT   = 'Root task — triggers autonomous ETL agent'
AS
  CALL AUDIT.SP_AUTONOMOUS_ETL_AGENT(3, NULL);

ALTER TASK AUDIT.TASK_ETL_ORCHESTRATOR RESUME;
